version: "3.3"

services:
  postgres:
    image: postgres
    container_name: postgresdb
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - postgres
networks:
  postgres:
    driver: bridge